apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-lb
spec:
  rules:
  - http:
      paths:
      - path: /cases
        backend:
          serviceName: caseviewer
          servicePort: 80

